# Generated by Django 2.2.3 on 2019-07-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pictures", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="picturepost",
            name="num_likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        )
    ]
