# Generated by Django 2.2.3 on 2019-07-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("common", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="profile", options={"verbose_name_plural": "User Profiles"}
        )
    ]
